parameters:
    #home_path: test

services:
    my_service:
        class:       Services\MyServiceImpl
        #file:       Services/MyServiceImpl.php
        #arguments: [@my_message]
        calls: 
             - [setMyMessage, [@my_message]]
             - [setMyValidator, [@my_validator]]
    my_message:
        class:       Services\MyMessageImpl
        #file:       Services/MyMessageImpl.php
        arguments: [@my_dao]
    my_validator:
        class:       Services\MyValidatorImpl
    my_dao:
        class:       Services\MyDaoImpl
    my_config:
        class: MyConfig
        file: %home_path%/Services/MyConfig.php
        calls:
            - [setConfig, [@zend_config_xml]]
    zend_config_xml:
        class: Zend_Config_Xml
        arguments: ['../configs/configs.xml', 'production']       
